services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - ./portainer_data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxynet
    ports:
      - 8000
      - 9443
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`zachtaiji.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - traefik.http.services.portainer.loadbalancer.server.port=9443
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true