services:
 portainer:
  image: portainer/portainer-ce:latest
  container_name: portainer
  volumes:
   - ./portainer_data:/data:rw
   - /var/run/docker.sock:/var/run/docker.sock
   - .certs:/certs
  networks:
   - reverse-proxynet
  restart: always
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=reverse-proxynet"      
   - "traefik.http.routers.portainer.rule=Host(`portainer.zachtaiji.com`) || Host (`www.portainer.zachtaiji.com`)"
   - "traefik.http.routers.portainer.entrypoints=web,websecure"
   - "traefik.http.routers.portainer.tls.certresolver=myresolver"
   - "traefik.http.routers.portainer.middlewares=https_redirect@docker,non_www@docker"
   # THIS IS THE INTERNAL PORT WE WANT TO EXPOSE TO HTTPS
   - "traefik.http.services.portainer.loadbalancer.server.port=9000"
 portainer_agent:
  image: portainer/agent:latest
  container_name: portainer_agent
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock:rw
   - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
   - /:/host
  restart: always
  ports:
   - 9001:9001
  networks:
   - reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true
